title: "Fully Funded Scholarships & Jobs 2026-2027 | JobScholarGuide"
author: "JobScholarGuide"

# ✅ New root domain (no subpath anymore)
url: "https://jobscholarguide.github.io"
baseurl: ""   # leave empty because site is at root of org.github.io

description: "Unlock global opportunities: scholarships, fellowships, internships, and jobs. Your roadmap to apply, qualify, and succeed in your career."

# Social links
twitter_username: jobscholarguide
facebook_username: jobscholarguide
linkedin_username: jobscholarguide
github_username: jobscholarguide

show_excerpts: true   # ✅ Show excerpts on homepage

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"
  skin: dark
  custom_css:
    - /assets/css/custom.css   # ✅ Custom button + styling

# Control where excerpts cut
excerpt_separator: "<!--more-->"

# Build settings
theme: minima

plugins:
  - jekyll-feed      # ✅ Generates feed.xml
  - jekyll-sitemap   # ✅ Generates sitemap.xml
  - jekyll-seo-tag   # ✅ Better SEO metadata

# Feed settings
feed:
  path: feed.xml     # ✅ Use standard feed.xml (not rss.xml)

# Sitemap settings
defaults:
  - scope:
      path: ""
    values:
      sitemap: true
