title: "Fully Funded Scholarships & Jobs 2026-2027 | JobScholarGuide"
author: "JobScholarGuide"

# ✅ Root domain (no subpath anymore)
url: "https://jobscholarguide.github.io"
baseurl: ""   # Leave empty since site is at root

description: "Unlock global opportunities: scholarships, fellowships, internships, and jobs. Your roadmap to apply, qualify, and succeed in your career."

# Social links (used by jekyll-seo-tag)
twitter_username: jobscholarguide
facebook_username: jobscholarguide
#linkedin_username: jobscholarguide
#github_username: jobscholarguide

show_excerpts: true   # ✅ Show excerpts on homepage

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"
  skin: dark
  custom_css:
    - /assets/css/custom.css   # ✅ Custom button + styling

# Control where excerpts cut
excerpt_separator: "<!--more-->"

# Build settings
theme: minima

plugins:
  - jekyll-feed      # ✅ Generates feed.xml automatically
  - jekyll-sitemap   # ✅ Generates sitemap.xml automatically
  - jekyll-seo-tag   # ✅ Better SEO metadata
  - jekyll-paginate  # ✅ Homepage pagination (better crawlability)

# Feed settings
feed:
  path: feed.xml     # ✅ Use standard feed.xml (Google recognizes this)

# Sitemap + Canonical settings
defaults:
  - scope:
      path: ""
    values:
      sitemap: true
      canonical_url: "https://jobscholarguide.github.io"
